FileVersion = 1
Projects = {BeefBoy = {Path = "."}, CowieCLI = "*", "Atma.Common" = "*"}
Unlocked = ["CowieCLI"]

[Workspace]
StartupProject = "BeefBoy"

[Configs.Debug.Win64]
ConfigSelections = {CowieCLI = {Platform = "Win32"}}
