FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Emu\\Memory.bf", "src\\Emu\\CPU.bf", "src\\CLICommands\\CLICommands.bf", "src\\Program.bf", "src\\Emu\\Instructions\\JumpFunctions.bf"]

[MainWindow]
X = 483
Y = 70
Width = 1200
Height = 1017
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 259.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 113.2076
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1367.0
RequestedHeight = 150.0
SizePriority = 1367.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CLICommands.bf"
TabWidth = 138.6793
Type = "SourceViewPanel"
FilePath = "src\\CLICommands\\CLICommands.bf"
CursorPos = 1287
VertPos = 336.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Memory.bf"
TabWidth = 102.8302
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Memory.bf"
CursorPos = 2859
VertPos = 816.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 103.7736
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 2211
VertPos = 624.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CPU.bf"
TabWidth = 79.24529
Type = "SourceViewPanel"
FilePath = "src\\Emu\\CPU.bf"
CursorPos = 23660
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "JumpFunctions.bf"
TabWidth = 130.9434
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Instructions\\JumpFunctions.bf"
CursorPos = 2867
VertPos = 352.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 248.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 117.9245
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 118.8679
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 95.28303
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.717
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.3208
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 92.45284
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.05661
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.79246
Type = "WatchPanel"
Columns = [{Width = 222.0}, {Width = 222.0}, {Width = 222.0}]
Items = [""]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 78.30189
Type = "AutoWatchPanel"
Columns = [{Width = 222.0}, {Width = 315.0}, {Width = 222.0}]
