FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\Emu\\Memory.bf", "src\\Emu\\Interrupts.bf", "src\\Emu\\CPU.bf", "src\\Display.bf", "src\\Emu\\PPU.bf", "src\\Misc\\Utils.bf", "src\\Program.bf", "src\\Emu\\Instructions\\MiscellaneousFunctions.bf", "src\\Emu\\Instructions\\CallFunctions.bf", "src\\Emu\\CB.bf", "src\\Emu\\Instructions\\JumpFunctions.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Array.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Graphics\\Rendering\\Texture\\Texture.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Platform\\OpenGL\\Graphics\\Rendering\\GL_Texture.bf", "src\\CLICommands\\CLICommands.bf"]

[MainWindow]
X = 720
Y = 26
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 259.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 113.2076
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1367.0
RequestedHeight = 150.0
SizePriority = 1367.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Utils.bf"
TabWidth = 79.24529
Type = "SourceViewPanel"
FilePath = "src\\Misc\\Utils.bf"
CursorPos = 33
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MiscellaneousFunctions.bf"
TabWidth = 180.0
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Instructions\\MiscellaneousFunctions.bf"
CursorPos = 330
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CallFunctions.bf"
TabWidth = 120.566
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Instructions\\CallFunctions.bf"
CursorPos = 1309
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CB.bf"
TabWidth = 60.18868
Type = "SourceViewPanel"
FilePath = "src\\Emu\\CB.bf"
CursorPos = 17974
VertPos = 4136.12
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Array.bf"
TabWidth = 75.28303
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Array.bf"
CursorPos = 6358
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GL_Texture.bf"
TabWidth = 107.3585
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Platform\\OpenGL\\Graphics\\Rendering\\GL_Texture.bf"
CursorPos = 1080
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Texture.bf"
TabWidth = 85.66039
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Graphics\\Rendering\\Texture\\Texture.bf"
CursorPos = 4301
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 120.7547
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Display.bf"
TabWidth = 85.66039
Type = "SourceViewPanel"
FilePath = "src\\Display.bf"
CursorPos = 1069
VertPos = 592.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "PPU.bf"
TabWidth = 68.67925
Type = "SourceViewPanel"
FilePath = "src\\Emu\\PPU.bf"
CursorPos = 7883
VertPos = 3600.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Interrupts.bf"
TabWidth = 101.6981
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Interrupts.bf"
CursorPos = 1155
VertPos = 672.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CLICommands.bf"
TabWidth = 129.0566
Type = "SourceViewPanel"
FilePath = "src\\CLICommands\\CLICommands.bf"
CursorPos = 1295
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Memory.bf"
TabWidth = 93.20756
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Memory.bf"
CursorPos = 4078
VertPos = 1936.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 94.15095
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 2562
VertPos = 944.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CPU.bf"
TabWidth = 69.62265
Type = "SourceViewPanel"
FilePath = "src\\Emu\\CPU.bf"
CursorPos = 1635
VertPos = 1120.0
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "JumpFunctions.bf"
TabWidth = 130.9434
Type = "SourceViewPanel"
FilePath = "src\\Emu\\Instructions\\JumpFunctions.bf"
CursorPos = 3358
ProjectName = "BeefBoy"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 248.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 117.9245
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 118.8679
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 95.28303
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.717
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.3208
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 92.45284
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.05661
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.79246
Type = "WatchPanel"
Columns = [{Width = 222.0}, {Width = 222.0}, {Width = 222.0}]
Items = [""]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 78.30189
Type = "AutoWatchPanel"
Columns = [{Width = 222.0}, {Width = 315.0}, {Width = 222.0}]
